version: '3.8'
services:
  app:
    image: phamtuankhoi/devicemanage-be-app:latest
    # platform: linux/amd64
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=mysql_db
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=Mysql7!js
      - MYSQL_DATABASE=nestjs_typeorm
      - MYSQL_SYNCHRONIZE=true
    depends_on:
      - mysql_db
    # restart: unless-stopped
    restart: always

  mysql_db:
    image: mysql:8.0
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql7!js
      - MYSQL_DATABASE=nestjs_typeorm
    ports:
      - '3306:3306' # Dùng 3306 nếu trống, hoặc thay bằng 3307 nếu cần
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
# docker-compose -f docker-compose.be.yml up -d
