version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: mysql_nestjs
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mysql7!js
      MYSQL_DATABASE: nestjs_typeorm
      MYSQL_USER: root
      MYSQL_PASSWORD: Mysql7!js
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # app:
  #   build: .
  #   container_name: nestjs_app
  #   restart: always
  #   depends_on:
  #     - mysql
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_PORT: 3306
  #     MYSQL_DATABASE: nestjs_typeorm
  #     MYSQL_USERNAME: root
  #     MYSQL_PASSWORD: Mysql7!js
  #   ports:
  #     - "3000:3000"
  #   command: ["npm", "run", "start:prod"]

volumes:
  mysql_data:
